#!/usr/bin/env bash

# these are the only packages that will be installed in the chroot
PACKAGES='linux bash coreutils vi vim perl pacman sudo curl'

if [ -d ./arch-fs ];
then
	echo ERROR!: The root filesystem for the Arch Linux chroot already exists.
	echo Use \`./start-chroot\` to start the chroot or \`./delete-chroot\` to delete it.
	exit
fi

echo Creating new Arch Linux root filesystem...
mkarchroot ./arch-fs $PACKAGES	# create new arch root filesystem at ./arch-fs
echo Finished creating new Arch Linux root filesystem!
echo
echo Done!
