#!/usr/bin/env bash

# these are the only packages that will be installed in the chroot
PACKAGES='linux bash coreutils vi vim perl pacman sudo curl'

# do not allow creation if filesystem directory already exists
if [ -d ./arch-fs ];
then
	echo ERROR!: The root filesystem for the Arch Linux chroot already exists.
	echo Use \`./start-chroot\` to start the chroot or \`./delete-chroot\` to delete it.
	exit
fi

# install `devtools` if `mkarchroot` cannot be run
check_command="mkarchroot" # the command to evaluate
check_package="devtools" # the package the command belongs to
if ! [ `command -v "$check_command"` ];
then
	echo \`$check_command\` could not be found!
	echo Installing \`$check_package\` using pacman...
	echo
	if [ "$EUID" == "0" ]; then pacman -Sy --noconfirm --needed "$check_package"; else sudo pacman -Sy --noconfirm --needed "$check_package"; fi
	echo
	echo Finished installing \`devtools\`!
	echo
fi

# ensure `mkarchroot` will actually run
if ! [ `command -v "$check_command"` ];
then
	echo ERROR!: \`$check_command\` could not be installed!
	exit
fi

# use mkarchroot to create a root filesystem
echo Creating new Arch Linux root filesystem...
mkarchroot ./arch-fs $PACKAGES	# create new arch root filesystem at ./arch-fs
echo Finished creating new Arch Linux root filesystem!
echo
echo Done!
