#!/usr/bin/env bash
# File: start-chroot
# Author: Nicholas Girga
# Purpose: Use `arch-chroot` on a filesystem created with `create-chroot`.

# define mounting function
mount_arch_fs() {
	echo Mounting root filesystem for Arch Linux chroot...
	sudo mount --bind ./arch-fs ./arch-fs
	echo Finished mounting root filesystem for Arch Linux chroot!
}

# define umounting function
unmount_arch_fs() {
	echo Unmounting root filesystem for Arch Linux chroot...
	sudo umount ./arch-fs
	echo Finished unmounting root filesystem for Arch Linux chroot!
}

# check if filesystem exists
if ! [ -d ./arch-fs ];
then
	echo ERROR!: The root filesystem for the Arch Linux chroot does not exist.
	echo Use \`./create-chroot\` to create a new root filesystem for the Arch Linux chroot.
	exit
fi

# install `util-linux` if `mount` cannot be run
check_command="mount" # the command to evaluate
check_package="util-linux" # the package the command belongs to
if ! [ `command -v "$check_command"` ];
then
	echo \`$check_command\` could not be found!
	echo Installing \`$check_package\` using pacman...
	echo
	if [ "$EUID" == "0" ]; then pacman -Sy --noconfirm --needed "$check_package"; else sudo pacman -Sy --noconfirm --needed "$check_package"; fi
	echo
	echo Finished installing \`devtools\`!
	echo
fi

# ensure `mount` will actually run
if ! [ `command -v "$check_command"` ];
then
	echo ERROR!: \`$check_command\` could not be installed!
	exit
fi

# install `util-linux` if `umount` cannot be run
check_command="umount" # the command to evaluate
check_package="util-linux" # the package the command belongs to
if ! [ `command -v "$check_command"` ];
then
	echo \`$check_command\` could not be found!
	echo Installing \`$check_package\` using pacman...
	echo
	if [ "$EUID" == "0" ]; then pacman -Sy --noconfirm --needed "$check_package"; else sudo pacman -Sy --noconfirm --needed "$check_package"; fi
	echo
	echo Finished installing \`devtools\`!
	echo
fi

# ensure `umount` will actually run
if ! [ `command -v "$check_command"` ];
then
	echo ERROR!: \`$check_command\` could not be installed!
	exit
fi

# mount filesystem
mount_arch_fs
echo

# install `devtools` if `arch-chroot` cannot be run
check_command="arch-chroot" # the command to evaluate
check_package="devtools" # the package the command belogns to
if ! [ `command -v "$check_command"` ];
then
	echo \`$check_command\` could not be found!
	echo Installing \`$check_package\` using pacman...
	echo
	if [ "$EUID" == "0" ]; then pacman -Sy --noconfirm --needed "$check_package"; else sudo pacman -Sy --noconfirm --needed "$check_package"; fi
	echo
	echo Finished installing \`devtools\`!
	echo
fi

# ensure `arch-chroot` will actually run
if ! [ `command -v "$check_command"` ];
then
	echo ERROR!: \`$check_command\` could not be installed!
	echo
	unmount_arch_fs # unmount before exiting
	exit
fi

# start chroot using `arch-chroot`
mountpoint -q "./arch-fs" && echo Starting Arch Linux chroot... || { echo ERROR!: Arch Linux filesystem could not be mounted.; exit; }
sudo arch-chroot ./arch-fs
echo Arch Linux chroot exited!
echo

# unmount filesystem after chroot has been exited
unmount_arch_fs
echo
echo Done!
