#!/usr/bin/env bash

# check if filesystem exists
if ! [ -d ./arch-fs ];
then
	echo ERROR!: The root filesystem for the Arch Linux chroot does not exist.
	echo Use \`./create-chroot\` to create a new root filesystem for the Arch Linux chroot.
	exit
fi

# install devtools if `arch-chroot` cannot be run
if ! [ `command -v "arch-chroot"` ];
then
	echo \`arch-chroot\` could not be found!
	echo Installing \`devtools\` using pacman...
	echo
	if [ "$EUID" == "0" ]; then pacman -Sy --noconfirm --needed devtools; else sudo pacman -Sy --noconfirm --needed devtools; fi
	echo
	echo Finished installing \`devtools\`!
	echo
fi

# ensure `arch-chroot` will actually run before mounting the filesystem
if ! [ `command -v "arch-chroot"` ];
then
	echo ERROR!: \`arch-chroot\` could not be installed!
	exit
fi

# mount filesystem
echo Mounting root filesystem for Arch Linux chroot...
sudo mount --bind ./arch-fs ./arch-fs	# mount ./arch-fs
echo Finished mounting root filesystem for Arch Linux chroot!
echo

# start chroot
echo Starting Arch Linux chroot...
sudo arch-chroot ./arch-fs		# chroot ./arch-fs
echo Arch Linux chroot exited!
echo

# unmount filesystem after chroot has been exited
echo Unmounting root filesystem for Arch Linux chroot...
sudo umount ./arch-fs			# unmount ./arch-fs
echo Finished unmounting root filesystem for Arch Linux chroot!
echo
echo Done!
